name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build: # Build and push Docker image
    runs-on: ubuntu-latest
    environment: master

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug secrets and variables
        run: |
            echo "DOCKERHUB_USERNAME variable : $DOCKERHUB_USERNAME"
            echo "DOCKERHUB_TOKEN variable : $DOCKERHUB_TOKEN"
        env:
            DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ vars.DOCKERHUB_USERNAME }}/beermapping-multiarch:latest
